### ISSUE TITLE
°F gets extra conversion in Home

### ISSUE THREAD

**Issue by sgeba** [fjhorrillo/homebridge-airzone-cloud#25] opened 2022-10-15 13:31 UTC
I assume with the release of these in the US there is an issue with the use of °F instead of C. The temperature comes in to Home with all of the temperatures from the app converted again. Example - my AirzoneCloud is set for F and heat set to 68F. In the Home it treats the as a C temperature and converts it again to F resulting in showing 155F in Home. 

I temporarily set my airzonecloud in C and restarted the child bridge. Everything comes in correctly in home as the proper F temperature but won't be able to leave it that way. Any help / data / debug you need let me know!

**Comment by fjhorrillo** [comment] 2022-10-15 17:41
Hello @sgeba, could you send me the logs with the debug mode on in the plugin to check what is getting from your Airzone cloud, thanks in advance.

**Comment by sgeba** [comment] 2022-10-15 19:50
[homebridge-airzone.log.txt](https://github.com/fjhorrillo/homebridge-airzone-cloud/files/9792951/homebridge-airzone.log.txt)

don't know what data in here is sensitive if at all, I removed a few of the auth things, but the calls are all still there, let me know if you need something different.

**Comment by sgeba** [comment] 2022-11-06 02:29
Was the attached data any help?

**Comment by fjhorrillo** [comment] 2022-11-07 21:01
Hello, I checked your logs and I could see that your Airzone provide data in both unit (C & F). I saw an error setting the temperature with F and the error is regarding a maximum in C.
I'm going to test it with my phone in F as I guest that it will be the problem.
Let me some time, I will be back with news a son as possible.

**Comment by arcticwolf18** [comment] 2022-11-27 20:59
Hey there. Was just wondering if you had any input on this. Still an ongoing issue for me.

**Comment by fjhorrillo** [comment] 2022-12-10 00:42
Hi! I assume you have configured the temperature unit by system preference and also in my home app, right? I was checking in this way and as I could see the problem is that the iPhone always uses celsius. I'm going to adapt the plugin in this way but I need a bit of time to change all to only work with celsius and remove the option to change the unit.

**Comment by fjhorrillo** [comment] 2022-12-10 17:04
Fixed with version 0.3.3

**Comment by fjhorrillo** [comment] 2022-12-10 17:05
Fixed with version 0.3.3

**Closed by fjhorrillo** 2022-12-10 17:05 UTC
